### ISSUE TITLE
Where do you work?

### ISSUE THREAD

**Issue by yangli-io** [kriskowal/ama#1]

**Comment by yangli-io** [comment]
And what tech stack do you use

**Comment by kriskowal** [comment]
I’m working on RPC systems at Uber in San Francisco. We use Node.js for most communication with mobile clients. We have a distributed services architecture using [Ringpop](http://uber.github.io/ringpop/), [TChannel](http://uber.github.io/tchannel/), and Thrift, particularly [ThriftRW](https://github.com/thriftrw) for service to service communication. For a year, I was on the team that developed [Hyperbahn](https://github.com/uber/hyperbahn) for service discovery and routing.

**Comment by kriskowal** [comment]
Also, https://www.linkedin.com/in/kkowal

**Comment by kriskowal** [comment]
Now I work at [Agoric](https://agoric.com/).
